       SUBROUTINE UMAT(STRESS, STATEV, DDSDDE, STRAN, DSTRAN, TIME,
     # DTIME, TEMP, DTEMP, PREDEF, DPRED, CMNAME, NDI, NSHR, NTENS, 
     # NSTATV, PROPS, NPROPS, COORDS, DROT, PNEWDT, CELENT, DFGRD0, 
     # DFGRD1, NOEL, NPT, LAYER, KSPT, KSTEP, KINC)
	 
       IMPLICIT REAL*8(A-H,O-Z)
	   
       DIMENSION STRESS(NTENS), STATEV(NSTATV), DDSDDE(NTENS,NTENS)
       DIMENSION STRAN(NTENS), DSTRAN(NTENS), TEMP(1), DTEMP(1)
       DIMENSION PREDEF(1), DPRED(1), PROPS(NPROPS), COORDS(3)
       DIMENSION DROT(3,3), DFGRD0(3,3), DFGRD1(3,3)
       
	   ! PARAMETERS
       INTEGER, PARAMETER :: NUM_STEPS = 6
       REAL*8, PARAMETER :: MACHINE_EPSILON = 1.0D-8
       
	   ! LOCAL VARIABLES
       REAL*8 :: STRESS_UD(NTENS), STRESS_D(NTENS, NUM_STEPS) 
       REAL*8 :: STRAN_UD(NTENS), STRAN_D(NTENS, NUM_STEPS)
       REAL*8 :: EPSILON_D
       
	   ! INITIALIZE THE UNDISTURBED STRAIN VECTOR
       STRAN_UD = STRAN
       
	   ! LOOP OVER EACH PERTURBATION STEP
       DO I = 1, NUM_STEPS
       
	       ! PERTURB ONLY ONE COMPONENT OF THE STRAIN VECTOR AT A TIME
           STRAN_D = STRAN_UD
	       ! CALCULATE THE PERTURBATION VALUE BASED ON MACHINE EPSILON AND CURRENT STRAIN COMPONENT
           EPSILON_D = MAX(MACHINE_EPSILON, 
     #     ABS(MACHINE_EPSILON * STRAN_UD(I)))
           STRAN_D(I) = STRAN_UD(I) + EPSILON_D
           
	       ! COMPUTE THE DISTURBED STRESS MATRIX FOR THE PERTURBED STRAIN
           CALL MATERIAL_ROUTINE(STRESS_D(:, I), STATEV, STRAN_D, 
     #     DSTRAN, TIME, DTIME, TEMP, DTEMP, PREDEF, DPRED, CMNAME, 
     #     NDI, NSHR, NTENS, NSTATV, PROPS, NPROPS, COORDS, DROT, 
     #     PNEWDT, CELENT, DFGRD0, DFGRD1, NOEL, NPT, LAYER, KSPT, 
     #     KSTEP, KINC)
       
       ENDDO
       
	   ! COMPUTE THE UNDISTURBED STRESS VECTOR AND UPDATED HISTORY VARIABLES
       CALL MATERIAL_ROUTINE(STRESS_UD, STATEV, STRAN_UD, 
     # DSTRAN, TIME, DTIME, TEMP, DTEMP, PREDEF, DPRED, CMNAME, 
     # NDI, NSHR, NTENS, NSTATV, PROPS, NPROPS, COORDS, DROT, 
     # PNEWDT, CELENT, DFGRD0, DFGRD1, NOEL, NPT, LAYER, KSPT, 
     # KSTEP, KINC)
       
	   ! COMPUTE THE APPROXIMATED CONSISTENT JACOBIAN MATERIAL TANGENT
       DO I = 1, NTENS
           DO J = 1, NUM_STEPS
	           !CALCULATE THE PERTURBATION VALUE BASED ON MACHINE EPSILON AND CURRENT UNDISTURBED STRAIN COMPONENT
               EPSILON_D = MAX(MACHINE_EPSILON, 
     #         ABS(MACHINE_EPSILON * STRAN_UD(J)))
	           !COMPUTE THE FINITE DIFFERENCE APPROXIMATION OF THE TANGENT
               DDSDDE(I, J) = (STRESS_D(I, J) - 
     #         STRESS_UD(I)) / EPSILON_D
           ENDDO
       ENDDO
       
	   ! ASSIGN THE FINAL STRESS VECTOR
       STRESS = STRESS_UD
       
       RETURN
       END SUBROUTINE UMAT
      